# Generated by Django 3.2.8 on 2021-10-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetailpage',
            options={'verbose_name': 'Blog Post'},
        ),
    ]
