# Generated by Django 3.2.8 on 2021-10-13 15:29

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title_section', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.CharBlock()), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='user'))]),
        ),
    ]
