# Generated by Django 3.2.8 on 2021-10-14 05:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title_section', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('img', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.CharBlock(max_length=100)), ('button_page', wagtail.core.blocks.PageChooserBlock()), ('button_text', wagtail.core.blocks.CharBlock(required=True))]))], icon='user', template='streams/blocks/section.html'))]),
        ),
    ]
